---
title: "ST 558 Project 1"
author: "Marcus Lee"
date: "6/13/2021"
output: 
  github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE, warning = FALSE, message=FALSE}
library(ggplot2)
library(jsonlite)
library(knitr)
library(httr)
```


# JSON Data

# Packages used for reading JSON data in R


# Contact the NHL Records API

```{r}
base_url = "https://records.nhl.com/site/api"
```

```{r}
get_franchise = function(){
  full_url = paste0(base_url, "/franchise")
  franchise_text = content(GET(url=full_url), "text")
  franchise_json = fromJSON(franchise_text, flatten = T)
  return(franchise_json$data)
}
```

```{r}
get_franchise_team_totals = function(){
  full_url = paste0(base_url, "/franchise-team-totals")
  franchise_team_totals_text = content(GET(url=full_url), "text")
  franchise_team_totals_json = fromJSON(franchise_team_totals_text, flatten = T)
  return(franchise_team_totals_json$data)
}
```

```{r}
get_franchise_season_records = function(id){
  full_url = paste0(base_url, "/franchise-season-records?cayenneExp=franchiseId=",id)
  franchise_season_records_text = content(GET(url=full_url), "text")
  franchise_season_records_json = fromJSON(franchise_season_records_text, flatten = T)
  return(franchise_season_records_json$data)
}
```

```{r}
get_franchise_goalie_records = function(id){
  full_url = paste0(base_url, "/franchise-goalie-records?cayenneExp=franchiseId=",id)
  franchise_goalie_records_text = content(GET(url=full_url), "text")
  franchise_goalie_records_json = fromJSON(franchise_goalie_records_text, flatten = T)
  return(franchise_goalie_records_json$data)
}
```

```{r}
get_franchise_skater_records = function(id){
  full_url = paste0(base_url, "/franchise-skater-records?cayenneExp=franchiseId=",id)
  franchise_skater_records_text = content(GET(url=full_url), "text")
  franchise_skater_records_json = fromJSON(franchise_skater_records_text, flatten = T)
  return(franchise_skater_records_json$data)
}
```

```{r}
get_franchise_detail = function(id){
  full_url = paste0(base_url, "/franchise-detail?cayenneExp=mostRecentTeamId=",id)
  franchise_detail_text = content(GET(url=full_url), "text")
  franchise_detail_json = fromJSON(franchise_detail_text, flatten = T)
  return(franchise_detail_json$data)
}
```

```{r, echo=FALSE, warning=FALSE, message =FALSE}
id=1
franchise = get_franchise()
franchise_team_total = get_franchise_team_totals()
franchise_season_records = get_franchise_season_records(id)
franchise_goalie_records = get_franchise_skater_records(id)
franchise_skater_records = get_franchise_skater_records(id)
franchise_detail = get_franchise_detail(id)
```

```{r}
kable(franchise)
```


# Contact the NHL Stats API

```{r}
base_stats_url = "https://statsapi.web.nhl.com/api/v1"
#https://statsapi.web.nhl.com/api/v1/expands
```

```{r}
get_team_stats = function(){
  # Not sure if I am doing this correctly
  #?stats=statsSingleSeasonPlayoffs
  #?expand=team.stats
  full_url = paste0(base_stats_url, "/teams?expand=team.stats=")
  team.stats_text = content(GET(url=full_url), "text")
  team.stats_json = fromJSON(team.stats_text, flatten = T)
  team.stats2 <- team.stats[2]
  return(team.stats2)
  #return(team.stats_json$data)#This is giving me a null answer
  #return(team.stats_json)
  #return(team.stats_df)
}
```

```{r}
#id=2
team.stats = get_team_stats()
```

```{r}
# We are ignoring team.stats[1]
#team.stats2 <- team.stats[2]
```


```{r}
kable(team.stats)
```


```{r}
#wrapper function
wrapper_url = "https://statsapi.web.nhl.com/api/v1"
```

```{r}
get_wrapper = function(){
  # Not sure if I am doing this correctly
  # Probably not the most efficient way to do it
  team.roster_full_url = paste0(wrapper_url, "/teams?expand=team.roster=")
  person.names_full_url = paste0(wrapper_url, "/teams?expand=person.names=")
  team.schedule.next_full_url = paste0(wrapper_url, "/teams?expand=team.schedule.next=")
  team.schedule.previous_full_url = paste0(wrapper_url, "/teams?expand=team.schedule.previous=")
  team.stats_full_url = paste0(wrapper_url, "/teams?expand=team.stats=")
  #team_roster&season_full_url = paste0(wrapper_url, "/teams?expand=team.roster&season=")
  team.Id_full_url = paste0(wrapper_url, "/teams?expand=teamId=")
  stats_full_url = paste0(wrapper_url, "/teams?expand=stats=")
  
  team.roster_text = content(GET(url=team.roster_full_url), "text")
  person.names_text = content(GET(url=person.names_full_url), "text")
  team.schedule.next_text = content(GET(url=team.schedule.next_full_url), "text")
  team.schedule.previous_text = content(GET(url=team.schedule.previous_full_url), "text")
  team.stats_text = content(GET(url=team.stats_full_url), "text")
  #team_roster&season_text = content(GET(url=team_roster&season_full_url), "text")
  team.Id_text = content(GET(url=team.Id_full_url), "text")
  stats_text = content(GET(url=stats_full_url), "text")
  
  
  team.roster_json = fromJSON(team.roster_text, flatten = T)
  person.names_json = fromJSON(person.names_text, flatten = T)
  team.schedule.next_json = fromJSON(team.schedule.next_text, flatten = T)
  team.schedule.previous_json = fromJSON(team.schedule.previous_text, flatten = T)
  team.stats_json = fromJSON(team.stats_text, flatten = T)
  #team_roster&season_json = fromJSON(team_roster&season_text, flatten = T)
  team.Id_json = fromJSON(team.Id_text, flatten = T)
  stats_json = fromJSON(stats_text, flatten = T)
  wrapper_json <- list(team.roster_json,person.names_json, team.schedule.next_json,team.schedule.previous_json, team.stats_json, team.Id_json, stats_json)
  #return(wrapper_json)
  wrap2 <- list(team.roster[2],person.names[2],)
  #team.stats2 <- team.stats[2]
  #return(team.stats2)
  #return(team.stats_json)
}
```

```{r}
#Yeah, I am going stop here today, because I do not think I am doing the wrapper function correctly.
wrap = get_wrapper()
```








## More functions

## Wrapper functions

# Exploratory Data Analysis













